### PR TITLE
Performance improvements

### PR DESCRIPTION
**Pull request by mpospelov**
+ get rid of `Mechanize`  
+ use OJ for parsing JSON
+ cache methods definitions once `method_missing` is hit

### CODE REVIEW

**Comment by ebsalberto** [comment]
thanks @mpospelov have you tested all methods that use this to make sure it'll work?

**Comment by mpospelov** [comment]
@ebsalberto I smoke tested most of the pages. I think everything should work fine, there is a small chance that some edge cases are missing

**Comment by mpospelov** [comment]
@ebsalberto I found a problem that tests on `API` repo side should be modified to support new library. I'll create a separate PR for it too

**Comment by ebsalberto** [comment]
@mpospelov Has this been fixed on the separate PR? I'm keen on merging this

**Comment by mpospelov** [comment]
I fixed it on https://github.com/Maxihost/API/pull/622 PR but didn’t have a chance to extract test fixes into separate one, will handle it tomorrow

**Comment by mpospelov** [comment]
@ebsalberto I attached a separate PR https://github.com/Maxihost/API/pull/634

**Pull request merged**
